### ISSUE TITLE
Error when checking currency of invalid content hosts

### ISSUE THREAD

**Issue by stdevel** [stdevel/check_katello_currency#2]
When checking an invalid content host (*e.g. the Foreman/Katello host*), the plugin crashes:
```
DEBUG:check_katello_currency:Checking system 'st-katello01.stankowic.loc'...
Traceback (most recent call last):
  File "./check_katello_currency.py", line 547, in <module>
    main(options)
  File "./check_katello_currency.py", line 533, in main
    check_systems()
  File "./check_katello_currency.py", line 87, in check_systems
    SYSTEM_ERRATA[system]["content_facet_attributes"]["errata_counts"]
KeyError: 'content_facet_attributes'
```

**Comment by stdevel** [comment]
Finally fixed in commit 5ea6502716a6508b0a3add87cef529f9b34af1f3
