### ISSUE TITLE
Generic statistics are broken if a system has no Katello agent installed

### ISSUE THREAD

**Issue by stdevel** [stdevel/check_katello_currency#5]
Checking generic statistics breaks if a system has no Katello agent (*resulting in missing `content_facet_attributes` dictionary*):

```
...
Traceback (most recent call last):
File "/usr/lib64/nagios/plugins/check_katello_currency", line 567, in <module>
    main(options)
  File "/usr/lib64/nagios/plugins/check_katello_currency", line 551, in main
    check_stats()
  File "/usr/lib64/nagios/plugins/check_katello_currency", line 188, in check_stats
    bugs_warn = [x for x in SYSTEM_ERRATA if SYSTEM_ERRATA[x]["content_facet_attributes"]["errata_counts"]["bugfix"] >= options.bugs_warn]
KeyError: 'content_facet_attributes'
```

**Comment by stdevel** [comment]
Fixed in commit f6cf5f6efa46ba8ea9763d0a3cd14b1a4602abe7.
